import type { Identifiable } from './Identifiable.js'

/**
 * Identifies an Entity.
 *
 * "Many objects represent a thread of continuity and identity, going through a lifecycle,
 * though their attributes may change."
 *
 * An entity is characterized by:
 * - Having a distinct identity that runs through time and different representations
 * - The identity may come from external sources or be generated by the system
 * - The model must define what it means to be the same thing
 *
 * @typeParam T - the aggregate root type this entity belongs to
 * @typeParam ID - the identifier type
 *
 * @see AggregateRoot
 * @see Identifier
 */
export interface Entity<T, ID> extends Identifiable<ID> {}
